server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "test"
    password: "test"
    url: "jdbc:postgresql://localhost:5470/test"
  flyway:
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: "localhost:9092"
    topics:
      first-topic:
        name: "com.szalai.eventdriven.publish.topic.v1"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: "http://localhost:8089"

    properties:
      auto:
        register:
          schemas: true